/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingsRouteImport } from './routes/trainings'
import { Route as SpeakingRouteImport } from './routes/speaking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PublicationsRouteImport } from './routes/publications'
import { Route as MachineLearningDeploymentRouteImport } from './routes/machine-learning-deployment'
import { Route as LlmSecurityAgenticAiSecurityRouteImport } from './routes/llm-security-agentic-ai-security'
import { Route as LlmDeploymentRouteImport } from './routes/llm-deployment'
import { Route as GizlilikPolitikasiRouteImport } from './routes/gizlilik-politikasi'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as AiSecurityInDefenseRouteImport } from './routes/ai-security-in-defense'
import { Route as AiRedTeamingMasterclassRouteImport } from './routes/ai-red-teaming-masterclass'
import { Route as AiMlSecurityRouteImport } from './routes/ai-ml-security'
import { Route as AgenticAiMasterclassRouteImport } from './routes/agentic-ai-masterclass'
import { Route as IndexRouteImport } from './routes/index'

const TrainingsRoute = TrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => rootRouteImport,
} as any)
const SpeakingRoute = SpeakingRouteImport.update({
  id: '/speaking',
  path: '/speaking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicationsRoute = PublicationsRouteImport.update({
  id: '/publications',
  path: '/publications',
  getParentRoute: () => rootRouteImport,
} as any)
const MachineLearningDeploymentRoute =
  MachineLearningDeploymentRouteImport.update({
    id: '/machine-learning-deployment',
    path: '/machine-learning-deployment',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlmSecurityAgenticAiSecurityRoute =
  LlmSecurityAgenticAiSecurityRouteImport.update({
    id: '/llm-security-agentic-ai-security',
    path: '/llm-security-agentic-ai-security',
    getParentRoute: () => rootRouteImport,
  } as any)
const LlmDeploymentRoute = LlmDeploymentRouteImport.update({
  id: '/llm-deployment',
  path: '/llm-deployment',
  getParentRoute: () => rootRouteImport,
} as any)
const GizlilikPolitikasiRoute = GizlilikPolitikasiRouteImport.update({
  id: '/gizlilik-politikasi',
  path: '/gizlilik-politikasi',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSecurityInDefenseRoute = AiSecurityInDefenseRouteImport.update({
  id: '/ai-security-in-defense',
  path: '/ai-security-in-defense',
  getParentRoute: () => rootRouteImport,
} as any)
const AiRedTeamingMasterclassRoute = AiRedTeamingMasterclassRouteImport.update({
  id: '/ai-red-teaming-masterclass',
  path: '/ai-red-teaming-masterclass',
  getParentRoute: () => rootRouteImport,
} as any)
const AiMlSecurityRoute = AiMlSecurityRouteImport.update({
  id: '/ai-ml-security',
  path: '/ai-ml-security',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenticAiMasterclassRoute = AgenticAiMasterclassRouteImport.update({
  id: '/agentic-ai-masterclass',
  path: '/agentic-ai-masterclass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agentic-ai-masterclass': typeof AgenticAiMasterclassRoute
  '/ai-ml-security': typeof AiMlSecurityRoute
  '/ai-red-teaming-masterclass': typeof AiRedTeamingMasterclassRoute
  '/ai-security-in-defense': typeof AiSecurityInDefenseRoute
  '/experience': typeof ExperienceRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/llm-deployment': typeof LlmDeploymentRoute
  '/llm-security-agentic-ai-security': typeof LlmSecurityAgenticAiSecurityRoute
  '/machine-learning-deployment': typeof MachineLearningDeploymentRoute
  '/publications': typeof PublicationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/trainings': typeof TrainingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agentic-ai-masterclass': typeof AgenticAiMasterclassRoute
  '/ai-ml-security': typeof AiMlSecurityRoute
  '/ai-red-teaming-masterclass': typeof AiRedTeamingMasterclassRoute
  '/ai-security-in-defense': typeof AiSecurityInDefenseRoute
  '/experience': typeof ExperienceRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/llm-deployment': typeof LlmDeploymentRoute
  '/llm-security-agentic-ai-security': typeof LlmSecurityAgenticAiSecurityRoute
  '/machine-learning-deployment': typeof MachineLearningDeploymentRoute
  '/publications': typeof PublicationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/trainings': typeof TrainingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agentic-ai-masterclass': typeof AgenticAiMasterclassRoute
  '/ai-ml-security': typeof AiMlSecurityRoute
  '/ai-red-teaming-masterclass': typeof AiRedTeamingMasterclassRoute
  '/ai-security-in-defense': typeof AiSecurityInDefenseRoute
  '/experience': typeof ExperienceRoute
  '/gizlilik-politikasi': typeof GizlilikPolitikasiRoute
  '/llm-deployment': typeof LlmDeploymentRoute
  '/llm-security-agentic-ai-security': typeof LlmSecurityAgenticAiSecurityRoute
  '/machine-learning-deployment': typeof MachineLearningDeploymentRoute
  '/publications': typeof PublicationsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/speaking': typeof SpeakingRoute
  '/trainings': typeof TrainingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agentic-ai-masterclass'
    | '/ai-ml-security'
    | '/ai-red-teaming-masterclass'
    | '/ai-security-in-defense'
    | '/experience'
    | '/gizlilik-politikasi'
    | '/llm-deployment'
    | '/llm-security-agentic-ai-security'
    | '/machine-learning-deployment'
    | '/publications'
    | '/sitemap.xml'
    | '/speaking'
    | '/trainings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agentic-ai-masterclass'
    | '/ai-ml-security'
    | '/ai-red-teaming-masterclass'
    | '/ai-security-in-defense'
    | '/experience'
    | '/gizlilik-politikasi'
    | '/llm-deployment'
    | '/llm-security-agentic-ai-security'
    | '/machine-learning-deployment'
    | '/publications'
    | '/sitemap.xml'
    | '/speaking'
    | '/trainings'
  id:
    | '__root__'
    | '/'
    | '/agentic-ai-masterclass'
    | '/ai-ml-security'
    | '/ai-red-teaming-masterclass'
    | '/ai-security-in-defense'
    | '/experience'
    | '/gizlilik-politikasi'
    | '/llm-deployment'
    | '/llm-security-agentic-ai-security'
    | '/machine-learning-deployment'
    | '/publications'
    | '/sitemap.xml'
    | '/speaking'
    | '/trainings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenticAiMasterclassRoute: typeof AgenticAiMasterclassRoute
  AiMlSecurityRoute: typeof AiMlSecurityRoute
  AiRedTeamingMasterclassRoute: typeof AiRedTeamingMasterclassRoute
  AiSecurityInDefenseRoute: typeof AiSecurityInDefenseRoute
  ExperienceRoute: typeof ExperienceRoute
  GizlilikPolitikasiRoute: typeof GizlilikPolitikasiRoute
  LlmDeploymentRoute: typeof LlmDeploymentRoute
  LlmSecurityAgenticAiSecurityRoute: typeof LlmSecurityAgenticAiSecurityRoute
  MachineLearningDeploymentRoute: typeof MachineLearningDeploymentRoute
  PublicationsRoute: typeof PublicationsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SpeakingRoute: typeof SpeakingRoute
  TrainingsRoute: typeof TrainingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trainings': {
      id: '/trainings'
      path: '/trainings'
      fullPath: '/trainings'
      preLoaderRoute: typeof TrainingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/speaking': {
      id: '/speaking'
      path: '/speaking'
      fullPath: '/speaking'
      preLoaderRoute: typeof SpeakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publications': {
      id: '/publications'
      path: '/publications'
      fullPath: '/publications'
      preLoaderRoute: typeof PublicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/machine-learning-deployment': {
      id: '/machine-learning-deployment'
      path: '/machine-learning-deployment'
      fullPath: '/machine-learning-deployment'
      preLoaderRoute: typeof MachineLearningDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-security-agentic-ai-security': {
      id: '/llm-security-agentic-ai-security'
      path: '/llm-security-agentic-ai-security'
      fullPath: '/llm-security-agentic-ai-security'
      preLoaderRoute: typeof LlmSecurityAgenticAiSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llm-deployment': {
      id: '/llm-deployment'
      path: '/llm-deployment'
      fullPath: '/llm-deployment'
      preLoaderRoute: typeof LlmDeploymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gizlilik-politikasi': {
      id: '/gizlilik-politikasi'
      path: '/gizlilik-politikasi'
      fullPath: '/gizlilik-politikasi'
      preLoaderRoute: typeof GizlilikPolitikasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-security-in-defense': {
      id: '/ai-security-in-defense'
      path: '/ai-security-in-defense'
      fullPath: '/ai-security-in-defense'
      preLoaderRoute: typeof AiSecurityInDefenseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-red-teaming-masterclass': {
      id: '/ai-red-teaming-masterclass'
      path: '/ai-red-teaming-masterclass'
      fullPath: '/ai-red-teaming-masterclass'
      preLoaderRoute: typeof AiRedTeamingMasterclassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-ml-security': {
      id: '/ai-ml-security'
      path: '/ai-ml-security'
      fullPath: '/ai-ml-security'
      preLoaderRoute: typeof AiMlSecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agentic-ai-masterclass': {
      id: '/agentic-ai-masterclass'
      path: '/agentic-ai-masterclass'
      fullPath: '/agentic-ai-masterclass'
      preLoaderRoute: typeof AgenticAiMasterclassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenticAiMasterclassRoute: AgenticAiMasterclassRoute,
  AiMlSecurityRoute: AiMlSecurityRoute,
  AiRedTeamingMasterclassRoute: AiRedTeamingMasterclassRoute,
  AiSecurityInDefenseRoute: AiSecurityInDefenseRoute,
  ExperienceRoute: ExperienceRoute,
  GizlilikPolitikasiRoute: GizlilikPolitikasiRoute,
  LlmDeploymentRoute: LlmDeploymentRoute,
  LlmSecurityAgenticAiSecurityRoute: LlmSecurityAgenticAiSecurityRoute,
  MachineLearningDeploymentRoute: MachineLearningDeploymentRoute,
  PublicationsRoute: PublicationsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SpeakingRoute: SpeakingRoute,
  TrainingsRoute: TrainingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
